package by.naxa.learning;

/**
 * Q: Given the following code, in the generated bytecode, what are the types of {@code X} and {@code T}?
 * A: They are both Objects.
 */
class MyClass<X> {
    <T> MyClass(T t) {
        // ...
    }
}

public class Test29 {
    public static void main(String[] args) {
        MyClass<Integer> myObject = new MyClass<>("");
    }
}
